#!/usr/bin/env python3
"""Evaluate the first partial Gemma sequence-expansion candidate for YV.

A149 is intentionally simple:
- retrieval universe stays all 2,105 active v31 occupation-name identities;
- baseline representation is the existing canonical label + distinct definition + alternatives;
- for the 149 concepts generated by the frozen Gemma hour run, append the eight
  teacher phrases to that concept's BM25 document;
- teacher phrases are NOT exact surfaces and do not change the short-query surface guard;
- no opened evaluation query is used to construct, filter, weight, or prune the corpus.

This is opened architecture/development evidence only. It must not be used as blind
accuracy evidence or to tune on the evaluated queries.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from evaluate_c2_job_title_router import relation_parent_ids
from evaluate_p80_lexical_ablation import BM25, as_list, expected_hash, fetch, load_jsonl, norm, tokens
from evaluate_pareto_c1 import rank_c1
from evaluate_yv_full_description_canonical import SOURCE_URL, phrase_present
from occupational_information_coverage import find_explicit_taxonomy_ids, record_map

EXPECTED_TEACHER_MODEL = "gemma-4-26b-a4b-it"
EXPECTED_TEACHER_ROWS = 149
EXPECTED_TEACHER_PHRASES = 149 * 8


def build_ranker(
    by_id: dict[str, dict[str, Any]],
    ids: list[str],
    teacher: dict[str, list[str]] | None = None,
):
    teacher = teacher or {}
    docs: dict[str, list[str]] = {}
    exact: dict[str, set[str]] = {}
    surface_tokens: dict[str, set[str]] = {}
    for cid in ids:
        concept = by_id[cid]
        label = str(concept.get("preferred_label") or "").strip()
        definition = str(concept.get("definition") or "").strip()
        real_definition = definition if definition and norm(definition) != norm(label) else ""
        alternatives = [x for x in as_list(concept.get("alternative_labels")) if norm(x) != norm(label)]
        canonical_surfaces = [label, *alternatives]
        extra = teacher.get(cid, [])
        docs[cid] = tokens(" ".join([label, real_definition, *alternatives, *extra]))
        exact[cid] = {norm(x) for x in canonical_surfaces if norm(x)}
        # Deliberately canonical-only: synthetic teacher phrases are language evidence,
        # never privileged exact-surface identity evidence.
        surface_tokens[cid] = {t for x in canonical_surfaces for t in tokens(x)}
    return BM25(docs, exact), exact, surface_tokens


def rank_ids(ranker: BM25, exact: dict[str, set[str]], surface_tokens: dict[str, set[str]], query: str) -> list[str]:
    return [cid for cid, _, _ in rank_c1(ranker, query, exact, surface_tokens)]


def strict_source_cases(
    source: dict[str, Any],
    by_id: dict[str, dict[str, Any]],
    active_occ: set[str],
) -> list[dict[str, Any]]:
    all_ids = set(by_id)
    records = record_map(source.get("data"))
    metadata = source.get("metadata")
    occupations_meta = metadata.get("occupations") if isinstance(metadata, dict) else None
    if not isinstance(occupations_meta, list):
        raise RuntimeError("Yrkesinformation missing metadata.occupations")

    job_title_surfaces_by_parent: dict[str, set[str]] = defaultdict(set)
    for concept in by_id.values():
        if concept.get("type") != "job-title":
            continue
        label = str(concept.get("preferred_label") or "").strip()
        if not label:
            continue
        for parent in relation_parent_ids(concept, by_id):
            job_title_surfaces_by_parent[parent].add(label)

    rows: list[dict[str, Any]] = []
    for meta in occupations_meta:
        if not isinstance(meta, dict):
            continue
        record = records.get(str(meta.get("slug") or ""))
        if not isinstance(record, dict):
            continue
        explicit = find_explicit_taxonomy_ids(record, all_ids) & active_occ
        if len(explicit) != 1:
            continue
        target = next(iter(explicit))
        query = str(record.get("work_task") or "").strip()
        if len(query) < 40:
            continue
        concept = by_id[target]
        surfaces = {
            str(concept.get("preferred_label") or ""),
            *as_list(concept.get("alternative_labels")),
            *job_title_surfaces_by_parent.get(target, set()),
        }
        if any(surface and phrase_present(query, surface) for surface in surfaces):
            continue
        rows.append({
            "source_slug": str(meta.get("slug") or ""),
            "target_id": target,
            "target_label": str(concept.get("preferred_label") or ""),
            "query": query,
        })
    if len(rows) != 17:
        raise RuntimeError(f"strict source-attested YV case drift: {len(rows)} != 17")
    return rows


def rank_metrics(cases: list[dict[str, Any]], ranked_by_case: list[list[str]]) -> dict[str, Any]:
    top1 = hit5 = 0
    rr = 0.0
    rows = []
    for case, ranked in zip(cases, ranked_by_case, strict=True):
        target = str(case["target_id"])
        rank = ranked.index(target) + 1 if target in ranked else None
        top1 += int(rank == 1)
        hit5 += int(rank is not None and rank <= 5)
        rr += 0.0 if rank is None else 1.0 / rank
        rows.append({
            "source_slug": case["source_slug"],
            "target_id": target,
            "target_label": case["target_label"],
            "rank": rank,
            "top5": ranked[:5],
        })
    n = len(cases)
    return {
        "cases": n,
        "top1": top1,
        "hit_at_5": hit5,
        "mrr": round(rr / n, 6),
        "rows": rows,
    }


def family_rank(ranked: list[str], by_id: dict[str, dict[str, Any]], expected: list[str]) -> int | None:
    needles = [norm(x) for x in expected if norm(x)]
    if not needles:
        return None
    for rank, cid in enumerate(ranked, start=1):
        label = norm(by_id[cid].get("preferred_label"))
        if any(needle in label for needle in needles):
            return rank
    return None


def stress_summary(
    cases: list[dict[str, Any]],
    by_id: dict[str, dict[str, Any]],
    ranked_by_case: list[list[str]],
) -> dict[str, Any]:
    rows = []
    for case, ranked in zip(cases, ranked_by_case, strict=True):
        expected = [str(x) for x in case.get("expect") or []]
        rank = family_rank(ranked, by_id, expected)
        rows.append({
            "id": case["id"],
            "category": case["category"],
            "query": case["query"],
            "expected": expected,
            "expected_family_rank": rank,
            "empty": not ranked,
            "top5": [str(by_id[cid].get("preferred_label") or cid) for cid in ranked[:5]],
        })

    categories: dict[str, Any] = {}
    for category in sorted({str(row["category"]) for row in rows}):
        subset = [row for row in rows if row["category"] == category]
        target = [row for row in subset if row["expected"]]
        negative = [row for row in subset if not row["expected"]]
        entry: dict[str, Any] = {"cases": len(subset)}
        if target:
            entry.update({
                "target_cases": len(target),
                "top1_family_hit": sum(row["expected_family_rank"] == 1 for row in target),
                "top5_family_hit": sum(
                    row["expected_family_rank"] is not None and row["expected_family_rank"] <= 5
                    for row in target
                ),
            })
        if negative:
            entry["negative_cases"] = len(negative)
            entry["correct_empty"] = sum(row["empty"] for row in negative)
        categories[category] = entry
    return {"categories": categories, "rows": rows}


def canonical_guard(
    cases: list[dict[str, Any]],
    ranker: BM25,
    exact: dict[str, set[str]],
    surface_tokens: dict[str, set[str]],
) -> dict[str, Any]:
    top1 = hit5 = 0
    for case in cases:
        expected = {str(x["concept_id"]) for x in case.get("must") or []}
        ranked = rank_ids(ranker, exact, surface_tokens, str(case["query"]))
        top1 += int(bool(ranked) and ranked[0] in expected)
        hit5 += int(any(cid in expected for cid in ranked[:5]))
    return {"cases": len(cases), "top1": top1, "hit_at_5": hit5}


def load_teacher(path: Path, active_occ: set[str]) -> tuple[dict[str, list[str]], str, bytes]:
    raw = path.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    rows = [json.loads(line) for line in raw.decode("utf-8").splitlines() if line.strip()]
    if len(rows) != EXPECTED_TEACHER_ROWS:
        raise RuntimeError(f"teacher row drift: {len(rows)} != {EXPECTED_TEACHER_ROWS}")
    out: dict[str, list[str]] = {}
    phrase_count = 0
    for row in rows:
        cid = str(row.get("concept_id") or "")
        phrases = [str(x).strip() for x in row.get("phrases") or [] if str(x).strip()]
        if cid not in active_occ:
            raise RuntimeError(f"teacher contains non-active YV identity {cid}")
        if cid in out:
            raise RuntimeError(f"duplicate teacher identity {cid}")
        if str(row.get("model") or "") != EXPECTED_TEACHER_MODEL:
            raise RuntimeError(f"teacher model drift for {cid}")
        if len(phrases) != 8:
            raise RuntimeError(f"teacher phrase count drift for {cid}: {len(phrases)}")
        out[cid] = phrases
        phrase_count += len(phrases)
    if phrase_count != EXPECTED_TEACHER_PHRASES:
        raise RuntimeError(f"teacher phrase total drift: {phrase_count}")
    compact = json.dumps(out, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return out, digest, compact


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--teacher", required=True)
    ap.add_argument("--registry", default="research/coverage/source-adapters.json")
    ap.add_argument("--stress", default="research/evaluation/v31/opened-live-semantic-stress-v1.json")
    ap.add_argument("--source-truth", default="research/benchmark/v31/p80-source-truth/yv-p80-source-truth.jsonl")
    ap.add_argument("--output", default="artifacts/gemma-a149-tournament.json")
    args = ap.parse_args()

    registry = json.loads(Path(args.registry).read_text(encoding="utf-8"))
    taxonomy_url = "https://data.jobtechdev.se/taxonomy/version/31/query/concepts-and-common-relations/concepts-and-common-relations.json"
    taxonomy_wire = fetch(taxonomy_url)
    taxonomy_sha = hashlib.sha256(taxonomy_wire).hexdigest()
    if taxonomy_sha != expected_hash(registry, "taxonomy-common-relations"):
        raise RuntimeError("taxonomy source drift")
    taxonomy = json.loads(taxonomy_wire)
    concepts = taxonomy.get("data", {}).get("concepts") or []
    by_id = {str(c["id"]): c for c in concepts if isinstance(c, dict) and c.get("id")}
    active_occ = {cid for cid, c in by_id.items() if c.get("type") == "occupation-name"}
    if len(active_occ) != 2105:
        raise RuntimeError(f"active YV universe drift: {len(active_occ)}")
    ids = sorted(active_occ)

    teacher, teacher_sha, compact = load_teacher(Path(args.teacher), active_occ)
    baseline_ranker, baseline_exact, baseline_surfaces = build_ranker(by_id, ids)
    a149_ranker, a149_exact, a149_surfaces = build_ranker(by_id, ids, teacher)

    source_wire = fetch(SOURCE_URL)
    source_sha = hashlib.sha256(source_wire).hexdigest()
    if source_sha != expected_hash(registry, "occupational-information"):
        raise RuntimeError("occupational-information source drift")
    strict = strict_source_cases(json.loads(source_wire), by_id, active_occ)
    baseline_strict = rank_metrics(
        strict,
        [rank_ids(baseline_ranker, baseline_exact, baseline_surfaces, row["query"]) for row in strict],
    )
    a149_strict = rank_metrics(
        strict,
        [rank_ids(a149_ranker, a149_exact, a149_surfaces, row["query"]) for row in strict],
    )
    if (baseline_strict["top1"], baseline_strict["hit_at_5"]) != (6, 9):
        raise RuntimeError(f"strict baseline parity failed: {baseline_strict['top1']}/{baseline_strict['hit_at_5']}")

    stress = json.loads(Path(args.stress).read_text(encoding="utf-8"))
    yv_stress = stress.get("yv") or []
    if len(yv_stress) != 54:
        raise RuntimeError(f"YV stress suite drift: {len(yv_stress)}")
    baseline_stress = stress_summary(
        yv_stress,
        by_id,
        [rank_ids(baseline_ranker, baseline_exact, baseline_surfaces, str(case["query"])) for case in yv_stress],
    )
    a149_stress = stress_summary(
        yv_stress,
        by_id,
        [rank_ids(a149_ranker, a149_exact, a149_surfaces, str(case["query"])) for case in yv_stress],
    )
    expected_baseline = {"direct": 8, "colloquial": 2, "noisy": 5, "indirect": 3}
    for category, expected_hits in expected_baseline.items():
        actual = baseline_stress["categories"][category].get("top5_family_hit")
        if actual != expected_hits:
            raise RuntimeError(f"stress baseline parity failed for {category}: {actual} != {expected_hits}")

    source_truth = load_jsonl(Path(args.source_truth))
    if len(source_truth) != 333:
        raise RuntimeError(f"canonical source-truth drift: {len(source_truth)}")
    baseline_guard = canonical_guard(source_truth, baseline_ranker, baseline_exact, baseline_surfaces)
    a149_guard = canonical_guard(source_truth, a149_ranker, a149_exact, a149_surfaces)

    strict_teacher_targets = sum(row["target_id"] in teacher for row in strict)
    stress_target_coverage: dict[str, dict[str, int]] = {}
    teacher_labels = [norm(by_id[cid].get("preferred_label")) for cid in teacher]
    for category in ("direct", "colloquial", "noisy", "indirect"):
        subset = [case for case in yv_stress if case.get("category") == category and case.get("expect")]
        covered = 0
        for case in subset:
            needles = [norm(x) for x in case.get("expect") or [] if norm(x)]
            covered += int(any(any(needle in label for needle in needles) for label in teacher_labels))
        stress_target_coverage[category] = {"target_cases": len(subset), "teacher_family_covered": covered}

    compact_gzip = gzip.compress(compact, compresslevel=9, mtime=0)
    result = {
        "schema_version": 1,
        "status": "opened partial A architecture diagnostic; no runtime promotion",
        "candidate": {
            "id": "YV-A149-Gemma4-26B-sequence-expansion-v0",
            "universe": 2105,
            "teacher_expanded_concepts": len(teacher),
            "teacher_phrases": sum(len(v) for v in teacher.values()),
            "representation": "full canonical YV BM25 + eight Gemma phrases appended for 149 concepts; teacher phrases are not exact surfaces",
            "teacher_model": EXPECTED_TEACHER_MODEL,
            "teacher_jsonl_sha256": teacher_sha,
        },
        "sources": {
            "taxonomy_sha256": taxonomy_sha,
            "occupational_information_sha256": source_sha,
            "stress_path": args.stress,
        },
        "coverage": {
            "strict17_target_concepts_expanded": strict_teacher_targets,
            "stress_target_family_coverage": stress_target_coverage,
        },
        "size": {
            "incremental_compact_teacher_json_raw_bytes": len(compact),
            "incremental_compact_teacher_json_gzip9_bytes": len(compact_gzip),
            "rough_linear_full_2105_projection_gzip9_bytes": round(len(compact_gzip) * 2105 / len(teacher)),
            "projection_warning": "linear projection only; not a measured full-corpus artifact",
        },
        "strict_source_attested_17": {
            "baseline_full_canonical": baseline_strict,
            "gemma_a149": a149_strict,
        },
        "opened_stress_54": {
            "baseline_full_canonical": baseline_stress,
            "gemma_a149": a149_stress,
        },
        "canonical_source_truth_333": {
            "baseline_full_canonical": baseline_guard,
            "gemma_a149": a149_guard,
        },
        "evidence_warning": "17-case and 54-case suites are already-opened development evidence. This result may falsify/compare architectures, not establish independent user accuracy or tune thresholds.",
    }

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    compact_print = {
        "candidate": result["candidate"],
        "coverage": result["coverage"],
        "size": result["size"],
        "strict_source_attested_17": {
            key: {k: v for k, v in value.items() if k != "rows"}
            for key, value in result["strict_source_attested_17"].items()
        },
        "opened_stress_categories": {
            key: value["categories"] for key, value in result["opened_stress_54"].items()
        },
        "canonical_source_truth_333": result["canonical_source_truth_333"],
        "output": str(out),
    }
    print(json.dumps(compact_print, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
