#!/usr/bin/env node
import fs from 'node:fs';
import crypto from 'node:crypto';
import Fuse from 'fuse.js';

const YV_COMMIT='1ad8c389a4f43caa5a704843487ca94419bf745a';
const YV_SEARCH_UTILS_BLOB='1eb706399ff97634b556164061e651a024b98003';
const KV_ENGINE_BLOB='bd255b894d39b9e8d628998cf8b749c71d529a3f';
const FUSE_VERSION='7.5.0';
const YV_URL='https://data.arbetsformedlingen.se/yrke/yrkesvaljaren/v1/yrkesvaljaren-t31.json';
const YV_SHA='1036f9525416fac4ce475c1c1d3909b9e2849ebcf7094ffd38104955e4c2ee49';
const KV_URL='https://data.arbetsformedlingen.se/kompetens/kompetensvaljaren/v1/kompetensvaljaren-t31.json';
const KV_SHA='da83f26bf316971caa407364d8feae6f791203bff5758e674cace3d919e4b524';
const MAX_WEAK_FUZZY_RESULTS=3, MIN_FUZZY_SCORE=.4, MAX_FUZZY_SCORE=.84;
const SKILL_CATEGORIES=['regulated_skills','essential_skills','optional_skills','calculated_skills','related_skills'];
const DEFAULT_BUCKET_WEIGHTS=[10,9,8,7,6,5,4,3,2,1], WEIGHT_BUCKET_SIZE=50, MAX_WEIGHTED_SKILL_DEPTH=500;

function args(){let journeys='research/personas/v31/journeys.jsonl',output='artifacts/track1-persona-product-replay-v31.json';for(let i=2;i<process.argv.length;i++){if(process.argv[i]==='--journeys')journeys=process.argv[++i];else if(process.argv[i]==='--output')output=process.argv[++i];else throw new Error(`unknown arg ${process.argv[i]}`);}return{journeys,output};}
function hash(b){return crypto.createHash('sha256').update(b).digest('hex');}
function norm(v){return String(v??'').normalize('NFC').toLowerCase().trim();}
function unique(v){const out=[],seen=new Set();for(const x of v)if(x&&!seen.has(x)){seen.add(x);out.push(x);}return out;}
function toIds(v){if(!v)return[];if(Array.isArray(v))return v.filter(x=>typeof x==='string');if(typeof v==='object')return Object.values(v).filter(x=>typeof x==='string');return[];}
function append(out,seen,ids){for(const id of ids)if(!seen.has(id)){seen.add(id);out.push(id);}}
async function fetchPinned(url,expected){const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);const b=Buffer.from(await r.arrayBuffer()),s=hash(b);if(s!==expected)throw new Error(`source drift ${url}: ${s}`);return{bytes:b,doc:JSON.parse(b.toString('utf8'))};}

// Current patched YV behavior replay. Contract is pinned to YV_COMMIT/YV_SEARCH_UTILS_BLOB.
function getDirectScore(label,q,tokens){if(label===q)return 1;if(tokens.length>1)return tokens.every(t=>label.includes(t))?.98:null;if(label.startsWith(q))return .99;if(label.includes(q))return .95;return null;}
function editDistance(a,b){const n=b.length;let prev=Array.from({length:n+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i,...new Array(n).fill(0)];for(let j=1;j<=n;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur;}return prev[n];}
function fuzzySubstring(text,q){const target=q.length,min=Math.max(3,target-2),max=Math.min(text.length,target+2);let best=99;for(let s=0;s<=text.length-min;s++)for(let l=min;l<=max&&s+l<=text.length;l++)best=Math.min(best,editDistance(q,text.slice(s,s+l)));return best<=Math.max(2,Math.floor(target*.25))?best:null;}
function rootMatch(q,label){q=norm(q);label=norm(label);if(label.includes(' ')){const d=editDistance(q,label);return d<=Math.max(2,Math.floor(q.length*.25))&&Math.abs(q.length-label.length)<=2;}return fuzzySubstring(label,q)!==null;}
function yvDisplay(r){return r.occupation_name_preferred_label?`${r.preferred_label} (${r.occupation_name_preferred_label})`:r.preferred_label;}
function yvIdentity(r){return r.type==='job-title'?`${r.id}|${r.occupation_name_id??''}`:r.id;}
function yvSort(rows){return rows.sort((a,b)=>b.score-a.score+0 || Number(b.weight??0)-Number(a.weight??0) || yvDisplay(a).localeCompare(yvDisplay(b),'sv'));}
class CurrentYv{
 constructor(items){this.items=items;this.fuse=new Fuse(items,{keys:['preferred_label'],includeScore:true,ignoreDiacritics:true,ignoreFieldNorm:true,threshold:.6,minMatchCharLength:1,ignoreLocation:true,distance:100});}
 search(query,max=10){if(!query)return[];const q=norm(query),tokens=q.split(' ').filter(Boolean),direct=[];for(const item of this.items){const s=getDirectScore(norm(item.preferred_label),q,tokens);if(s!==null)direct.push({...item,score:s});}if(direct.length)return yvSort(direct).slice(0,max);const raw=this.fuse.search(q);if(!raw.length)return[];const best=raw[0].score??1,candidates=[],seen=new Set();let strong=false;for(const fr of raw){const identity=yvIdentity(fr.item);if(seen.has(identity))continue;const rs=fr.score??1,base=1-rs;if(base<MIN_FUZZY_SCORE||rs>best+.12)continue;const root=rootMatch(q,norm(fr.item.preferred_label));if(root&&rs<=.25)strong=true;let score=base*.70+Number(fr.item.weight??0)*.10+(root ? .12 : 0);score=Math.min(MAX_FUZZY_SCORE,Math.max(MIN_FUZZY_SCORE,score));candidates.push({...fr.item,score});seen.add(identity);}if(!candidates.length)return[];const sorted=yvSort(candidates),limit=strong?Math.min(5,max):Math.min(MAX_WEAK_FUZZY_RESULTS,max);return sorted.slice(0,limit);}
}
function yvPublic(r){return{display:yvDisplay(r),type:r.type,id:r.id,occupation_id:r.type==='occupation-name'?r.id:(r.occupation_name_id??null),occupation_label:r.type==='job-title'?(r.occupation_name_preferred_label??null):r.preferred_label,weight:Number(r.weight??0),score:Number(r.score??0)};}

// Current KV behavior replay over published v31 data.
function collectSkills(raw){const skills={};for(const node of Object.values(raw||{})){if(!node||typeof node!=='object')continue;for(const cat of SKILL_CATEGORIES){const v=node[cat];if(!v||typeof v!=='object')continue;for(const [label,id] of Object.entries(v))if(typeof label==='string'&&typeof id==='string')skills[id]=label;}if(node.type===undefined&&!node.preferred_label)for(const [label,id] of Object.entries(node))if(typeof label==='string'&&typeof id==='string')skills[id]=label;}return skills;}
function expandWeighted(raw,ids,transferable,skills){const out=[],seen=new Set();for(const id of ids){if(id==='transferable_skills'){append(out,seen,transferable);continue;}const n=raw[id];if(n?.type==='ssyk-level-4'){append(out,seen,toIds(n.related_skills));continue;}if(skills[id])append(out,seen,[id]);}return out;}
function buildKv(doc){const raw=doc.data||{},skills=collectSkills(raw),transferable=toIds(raw.transferable_skills),globalWeighted=[],seen=new Set();append(globalWeighted,seen,transferable);for(const source of toIds(doc.metadata?.most_common_ssyk_level_4)){if(source==='transferable_skills')continue;append(globalWeighted,seen,expandWeighted(raw,toIds(raw[source]?.weighted_priority),transferable,skills));}const occupationToSsyk4={},ssyk4ToSsyk3={},shards=new Map();for(const [id,node] of Object.entries(raw)){if(!node||typeof node!=='object')continue;if(node.type==='occupation-name'&&typeof node['ssyk-level-4-id']==='string')occupationToSsyk4[id]=node['ssyk-level-4-id'];if(node.type==='ssyk-level-4'&&typeof node.ssyk_code_2012==='string')ssyk4ToSsyk3[id]=node.ssyk_code_2012.slice(0,3);}const getShard=s=>{if(!shards.has(s))shards.set(s,{ssyk4:{},occupations:{}});return shards.get(s);};for(const [id,node] of Object.entries(raw)){if(!node||typeof node!=='object')continue;if(node.type==='ssyk-level-4'){const s=ssyk4ToSsyk3[id];if(!s)continue;getShard(s).ssyk4[id]={relatedSkills:toIds(node.related_skills),weightedSkills:expandWeighted(raw,toIds(node.weighted_priority),transferable,skills)};}else if(node.type==='occupation-name'){const s4=occupationToSsyk4[id],s3=ssyk4ToSsyk3[s4];if(!s3)continue;getShard(s3).occupations[id]={preferredLabel:String(node.preferred_label??''),ssykLevel4Id:s4,regulatedSkills:toIds(node.regulated_skills),essentialSkills:toIds(node.essential_skills),optionalSkills:toIds(node.optional_skills),calculatedSkills:toIds(node.calculated_skills)};}}return{raw,skills,transferable,globalWeighted,occupationToSsyk4,ssyk4ToSsyk3,shards,mostCommonSkills:toIds(doc.metadata?.most_common_skills)};}
function splitTokens(v){return norm(v).split(/[\s\-_/(),.;:]+/).filter(Boolean);}
function directMatch(label,q){if(!label.includes(q))return null;if(label===q)return{kind:'exact'};if(label.startsWith(q))return{kind:'prefix'};const e=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),m=new RegExp(`(?:^|[\\s\\-_/(),.;:])${e}`).exec(label);if(m)return{kind:'wordBoundary',index:m.index};return{kind:'contains',index:label.indexOf(q)};}
function textScore(m){return m.kind==='exact'?10000:m.kind==='prefix'?8000:m.kind==='wordBoundary'?7000-Math.min(m.index,80)*8:m.kind==='contains'?5600-Math.min(m.index,120)*4:3200+m.score*80;}
function tier(m){return{exact:0,prefix:1,wordBoundary:2,contains:3,fuzzy:4}[m.kind];}
function order(m){if(m.kind==='exact'||m.kind==='prefix')return 0;if(m.kind==='fuzzy')return-m.score;return m.index;}
function weightMap(ids){const m=new Map();ids.forEach((id,i)=>{if(m.has(id)||i>=MAX_WEIGHTED_SKILL_DEPTH)return;const w=DEFAULT_BUCKET_WEIGHTS[Math.floor(i/WEIGHT_BUCKET_SIZE)]??0;if(w>0)m.set(id,w);});return m;}
function sortWeightMap(ids){const m=new Map();unique(ids).slice(0,MAX_WEIGHTED_SKILL_DEPTH).forEach((id,i)=>m.set(id,MAX_WEIGHTED_SKILL_DEPTH-i));return m;}
function firstNonZero(v){return v.find(x=>x!==0)??0;}
class CurrentKv{
 constructor(base){this.base=base;this.catalog=Object.entries(base.skills).map(([id,label])=>({id,label,normalized:norm(label)}));const tc=Object.entries(base.skills).flatMap(([skillId,label])=>splitTokens(label).map(token=>({skillId,token})));this.fuse=new Fuse(tc,{includeScore:true,shouldSort:true,ignoreLocation:false,ignoreFieldNorm:true,ignoreDiacritics:false,threshold:.25,distance:80,minMatchCharLength:3,keys:['token']});}
 search(query,max=5){const q=norm(query);if(!q)return[];const direct=new Map();for(const e of this.catalog){const m=directMatch(e.normalized,q);if(m)direct.set(e.id,m);}const fuzzy=new Map();if(q.length>=3)for(const r of this.fuse.search(q,{limit:150})){const conf=1-(r.score??1);if(conf<=0)continue;const old=fuzzy.get(r.item.skillId),os=old?.kind==='fuzzy'?old.score:0;fuzzy.set(r.item.skillId,{kind:'fuzzy',score:Math.max(os,conf*8)});}const matches=direct.size===0?fuzzy:new Map(fuzzy);if(direct.size)for(const [id,m] of direct)matches.set(id,m);const weighted=[...this.base.transferable,...this.base.globalWeighted],wm=weightMap(weighted),sm=sortWeightMap(weighted);const rows=this.catalog.filter(e=>matches.has(e.id)).map(e=>({id:e.id,label:e.label,match:matches.get(e.id),weightedRank:wm.get(e.id)??0,weightedSortWeight:sm.get(e.id)??0}));rows.sort((a,b)=>firstNonZero([(a.match.kind==='exact'?0:1)-(b.match.kind==='exact'?0:1),textScore(b.match)-textScore(a.match),tier(a.match)-tier(b.match),order(a.match)-order(b.match),b.weightedRank-a.weightedRank,b.weightedSortWeight-a.weightedSortWeight,a.label.localeCompare(b.label,'sv')]));return rows.slice(0,max).map(r=>({id:r.id,preferred_label:r.label,match:r.match.kind}));}
 hasContext(id){return !!this.base.occupationToSsyk4[id]||!!this.base.ssyk4ToSsyk3[id];}
 prioritized(occupationId,max=5){const s4=this.base.occupationToSsyk4[occupationId];if(!s4)return this.base.mostCommonSkills.slice(0,max).map(id=>({id,preferred_label:this.base.skills[id],rank:3})).filter(x=>x.preferred_label);const s3=this.base.ssyk4ToSsyk3[s4],shard=this.base.shards.get(s3),occ=shard?.occupations?.[occupationId];if(!occ)return this.base.mostCommonSkills.slice(0,max).map(id=>({id,preferred_label:this.base.skills[id],rank:3})).filter(x=>x.preferred_label);const related=shard?.ssyk4?.[s4]?.relatedSkills??[];const ranked=[[occ.regulatedSkills,9],[occ.essentialSkills,8],[occ.optionalSkills,7],[occ.calculatedSkills,6],[related,4]];const out=[],seen=new Set();for(const [id,rank] of ranked){if(seen.has(id)||!this.base.skills[id])continue;seen.add(id);out.push({id,preferred_label:this.base.skills[id],rank});if(out.length>=max)break;}return out.length?out:this.base.mostCommonSkills.slice(0,max).map(id=>({id,preferred_label:this.base.skills[id],rank:3})).filter(x=>x.preferred_label);}
}

async function main(){const a=args(),journeys=fs.readFileSync(a.journeys,'utf8').split(/\n/).filter(Boolean).map(JSON.parse),description=journeys.filter(j=>j.product.includes('DESCRIPTION')),included=journeys.filter(j=>!j.product.includes('DESCRIPTION')),[ys,ks]=await Promise.all([fetchPinned(YV_URL,YV_SHA),fetchPinned(KV_URL,KV_SHA)]),yv=new CurrentYv(ys.doc.data),kv=new CurrentKv(buildKv(ks.doc)),results=[];for(const j of included){if(j.first_query.startsWith('__AUTO_')){results.push({id:j.id,product:j.product,status:'deferred-deterministic-substitution',query:j.first_query});continue;}if(j.product==='YV'){const all=yv.search(j.first_query,50);results.push({id:j.id,product:j.product,query:j.first_query,result_count:all.length,visible:all.slice(0,j.recognition_budget).map(yvPublic),all:all.map(yvPublic),success_condition:j.success_condition});}else if(j.product==='KV'){const all=kv.search(j.first_query,50);results.push({id:j.id,product:j.product,query:j.first_query,result_count:all.length,visible:all.slice(0,j.recognition_budget),all,success_condition:j.success_condition});}else if(j.product==='YV_TO_KV'){const yrows=yv.search(j.first_query,10),paths=[];for(const r of yrows.slice(0,5)){const pub=yvPublic(r),occ=pub.occupation_id;paths.push({yv:pub,kv_context_valid:!!occ&&kv.hasContext(occ),kv_top5:occ?kv.prioritized(occ,5):[]});}results.push({id:j.id,product:j.product,query:j.first_query,yv_visible:yrows.slice(0,5).map(yvPublic),paths,success_condition:j.success_condition});}}
const out={schema_version:1,track:'1-current-yv-kv-findability',replay_contract:{yv_commit:YV_COMMIT,yv_search_utils_blob:YV_SEARCH_UTILS_BLOB,kv_engine_blob:KV_ENGINE_BLOB,fuse_js_version:FUSE_VERSION,classification:'behavior replay pinned to product source hashes; YV fuzzy context fix independently regression-tested in product repo'},sources:{yv:{url:YV_URL,sha256:hash(ys.bytes)},kv:{url:KV_URL,sha256:hash(ks.bytes)}},description_journeys_skipped:description.map(j=>j.id),included_journeys:included.length,results};fs.mkdirSync(a.output.substring(0,a.output.lastIndexOf('/')),{recursive:true});fs.writeFileSync(a.output,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({included_journeys:included.length,description_journeys_skipped:out.description_journeys_skipped,results:results.map(r=>({id:r.id,product:r.product,query:r.query,result_count:r.result_count??r.yv_visible?.length??null,visible:r.visible??r.yv_visible??null}))},null,2));}
await main();
